defaults:
  - env: random_goal
  - model: size12M
  - buffer: her
  - logger: tensorboard
  # Disable Hydra's Python logging-to-file (train.log)
  - override hydra/job_logging: disabled
  - _self_

logdir: logdir/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 0
deterministic_run: False
device: "cuda:0"

hydra:
  run:
    dir: ${logdir}

batch_size: 16
batch_length: 64
goal_type: full # first_row|row_by_row|full|argmax_full|log_prob|prob
prob_threshold: 0.5 # probability in [0,1]; compared in log-space
prob_threshold_step: 0.05 # bin width for threshold one-hot (21 bins total)
mission_text: False
wm_only: False
freeze_wm: False
train_text_only: False
load_from: null

env:
  goal_type: ${goal_type}
  stochastic_classes: ${model.rssm.discrete}
  stochastic_rows: ${model.rssm.stoch}
  goal_sample: buffer # buffer|text|random
  mission_text: ${mission_text}

model:
  goal_type: ${goal_type}
  mission_text: ${mission_text}
  wm_only: ${wm_only}
  freeze_wm: ${freeze_wm}
  train_text_only: ${train_text_only}
  prob_threshold: ${prob_threshold}
  prob_threshold_step: ${prob_threshold_step}

buffer:
  goal_type: ${goal_type}

# buffer:
#   batch_size: ${batch_size}
#   batch_length: ${batch_length}
#   max_size: 5e5
#   device: ${device}
#   storage_device: "cpu"
#   type: "her"
#   her_ratio: 0.8
#   her_strategy: final
#   n_envs: ${env.env_num}

trainer:
  steps: ${env.steps}
  pretrain: 0
  eval_every: 1e4
  eval_episode_num: ${env.eval_episode_num}
  batch_size: ${batch_size}
  batch_length: ${batch_length}
  train_ratio: ${env.train_ratio}
  video_pred_log: False
  params_hist_log: False
  obs_step_prob_log: False
  update_log_every: 5e3
  action_repeat: ${env.action_repeat}
  goal_sample: ${env.goal_sample}
  goal_type: ${goal_type}
  wm_only: ${wm_only}
  train_text_only: ${train_text_only}
