task: "random-goal_"
steps: 4.1e5
env_num: 1
action_repeat: 1
eval_episode_num: 10
train_ratio: 512
time_limit: 1000

seed: ${seed}
device: ${device}

size: [64, 64]
encoder:
  mlp_keys: "direction"
  cnn_keys: "image"
decoder:
  mlp_keys: "direction"
  cnn_keys: "image"

env_size: 10
agent_start_dir: 0
agent_start_pos_x: 1
agent_start_pos_y: 1
render_mode: "rgb_array"
